// export const DEFAULT_REDIS_HOST = 'localhost';
// export const DEFAULT_REDIS_PORT = '6379';
// export const DEFAULT_REDIS_DB = '0';
// export const DEFAULT_REDIS_USERNAME = '';
// export const DEFAULT_REDIS_PASSWORD = '';
// export const DEFAULT_REDIS_TLS = false;
// export const DEFAULT_STORE_INTERVAL = 30;
export const DEFAULT_KV_PREFIX = '';
export const DEFAULT_KV_URL = "redis://127.0.0.1:6379";